key: MYKEY
secret: MYSECRET
host: https://oauth.oclc.org
auth_url: https://oauth.oclc.org/auth
token_url: https://oauth.oclc.org/token
collection_management_api_url: https://circ.sd00.worldcat.org/LHR