key: MYKEY
secret: MYSECRET
host: https://oauth.oclc.org
auth_url: https://oauth.oclc.org/auth
token_url: https://oauth.oclc.org/token
lman_service_url: https://128807.share.worldcat.org/license-manager